export const data = [
  {
    id: "33211",
    make_id: "1000006",
    make_desc: "APRILIA",
    model_id: "1001841",
    model_desc: "CAPONORD",
    variant_id: "1015256",
    variant_desc: "1200 ABS",
    search_string: "APRILIA CAPONORD 1200 ABS (1197 cc)",
    motor_flag: "Bike",
    fuel_type_id: "1",
    fuel_type_desc: "Petrol",
    seating_capacity: "2",
    vehicle_image: "Aprilia-Caponord.jpg",
    search_count: "0",
    cc: "1197",
    segment_id: "1000004",
    segment_desc: "Motor cycle",
  },
  {
    "Vehicle Code": "1210110101         ",
    Make: "APRILIA                       ",
    Model: "CAPONORD                                          ",
    Variant: "1200 ABS                      ",
    "Body Type": "Motor Cycle",
    "Seating Capacity": "2",
    Power: "95.4",
    "Cubic Capacity": "1,197",
    "Grosss Vehicle Weight": "1",
    "Fuel Type": "Petrol",
    "No Of Wheels": "2",
    Abs: "Y",
    "Air Bags": "N",
    Length: "0",
    "Ex Showroom Price": "2,157,647",
    "Price Year": "2,017",
    Production: "Under Production",
    Manufacturing: "CBU ",
    "Vehicle Type": "MotorBike",
  },
];
